--CREATE OR ALTER TRIGGER UPD_CARDURI ON CARDURI
--INSTEAD OF UPDATE 
--AS
--BEGIN
	
--	UPDATE CD SET TIMESTAMP_END = GETDATE() FROM CARDURI_DATA CD 
--	INNER JOIN inserted ON CD.SERIE_CARD = inserted.SERIE_CARD AND CD.TIMESTAMP_END IS NULL

--	INSERT INTO CARDURI_DATA
--                         (SERIE_CARD, CLIENTID, PUNCTE, TIMESTAMP_START, TIMESTAMP_END)
--	SELECT SERIE_CARD,CLIENTID,PUNCTE,GETDATE(),NULL FROM inserted

--END

--CREATE OR ALTER TRIGGER INS_CARDURI ON CARDURI
--INSTEAD OF INSERT 
--AS
--BEGIN
	
--	INSERT INTO CARDURI_DATA
--                         (SERIE_CARD, CLIENTID, PUNCTE, TIMESTAMP_START, TIMESTAMP_END)
--	SELECT SERIE_CARD,CLIENTID,PUNCTE,GETDATE(),NULL FROM inserted

--END
--CREATE OR ALTER TRIGGER DEL_CARDURI ON CARDURI
--INSTEAD OF DELETE
--AS
--BEGIN
	
--	UPDATE CD SET TIMESTAMP_END = GETDATE() FROM CARDURI_DATA CD 
--	INNER JOIN deleted ON CD.SERIE_CARD = deleted.SERIE_CARD AND CD.TIMESTAMP_END IS NULL
--END



